# Numpy

## Video 3 - Tipos de datos

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [3]:
arr.dtype

dtype('int32')

In [4]:
arr = np.array([1,2,3,4], dtype="float64")
arr.dtype

dtype('float64')

In [5]:
arr = arr.astype(np.float64)

In [6]:
arr = np.array([0,1,2,3,4])
arr = arr.astype(np.bool_)
arr

array([False,  True,  True,  True,  True])

In [7]:
arr = np.array([0,1,2,3,4])
arr = arr.astype(np.string_)
arr

array([b'0', b'1', b'2', b'3', b'4'], dtype='|S11')

In [8]:
arr = np.array(['0','1','2','3','4'])
arr = arr.astype(np.int8)
arr

array([0, 1, 2, 3, 4], dtype=int8)

## Video 4 - Dimensiones 

In [11]:
scalar = np.array(42)
scalar.ndim

0

In [12]:
vector = np.array([1, 2, 3])
vector.ndim

1

In [17]:
matrix = np.array([[1, 2, 3], [4 ,5 ,6]])
matrix.ndim

2

In [19]:
tensor = np.array([[[1, 2, 3], [4 ,5 ,6]],[[1, 2, 3], [4 ,5 ,6]]])
tensor.ndim

3

#### Agregar o eliminar dimensiones

In [ ]:
vector = np.array([1, 2, 3], ndmin = 10)
vector.ndim

In [27]:
print(vector)

[[[[[[[[[[1 2 3]]]]]]]]]]


In [28]:
# Expandir dimensiones
# axis = 0 -> Filas
# axis = 1 -> Columnas

np.expand_dims(np.array([1, 2, 3]), axis = 0)

array([[1, 2, 3]])

In [31]:
print(vector, vector.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]] 10


In [32]:
vector_2 = np.squeeze(vector)
vector_2

array([1, 2, 3])