# Numpy

## Video 3 - Tipos de datos

In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [5]:
arr.dtype

dtype('int32')

In [7]:
arr = np.array([1,2,3,4], dtype="float64")
arr.dtype

dtype('float64')

In [8]:
arr = arr.astype(np.float64)

In [11]:
arr = np.array([0,1,2,3,4])
arr = arr.astype(np.bool_)
arr

array([False,  True,  True,  True,  True])

In [12]:
arr = np.array([0,1,2,3,4])
arr = arr.astype(np.string_)
arr

array([b'0', b'1', b'2', b'3', b'4'], dtype='|S11')

In [13]:
arr = np.array(['0','1','2','3','4'])
arr = arr.astype(np.int8)
arr

array([0, 1, 2, 3, 4], dtype=int8)